repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.9
    hooks:
      - id: typos

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2 # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
      - id: autopep8

  - repo: local
    hooks:
      - id: django-local
        name: "Django check breaking changes"
        entry: ./scripts/django_checks.sh
        language: script
        types: [python]

      - id: frontend-linting
        name: "Frontend Checks"
        entry: npx eslint --fix
        language: system
